---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-sc-pvc-rwo-100m
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi