---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-sc-pvc-rwx-200m
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Mi