---
apiVersion: v1
kind: Pod
metadata:
  name: my-pvpvc-pod
spec:
  volumes:
    - name: my-nfs-pvc-vol
      persistentVolumeClaim:
        claimName: my-nfs-pvc
  containers:
    - name: busybox
      image: busybox:latest
      volumeMounts:
        - mountPath: /data
          name: my-nfs-pvc-vol
      command:
        - "/bin/sh"
        - "-c"
        - "echo 'hello world' >> /data/hello.txt; sleep 3600"